version: "3.8"

services:
  postgres_forum: #use this name in the adminer login screen server
    image: postgres:13.1
    container_name: postgres_forum
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - forum_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - postgres_forum
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  queue_cache:
    image: redis:alpine
    container_name: queue_cache
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - queue_cache_data:/data


volumes:
  forum_data:
  queue_cache_data: