version: "3.8"

services:
  postgres_auth: #use this name in the adminer login screen server
    image: postgres:13.1
    container_name: postgres_auth
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - starter_auth_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    depends_on:
      - postgres_auth
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  starter_auth_data: