version: "3.8"

services:
  postgres_forum_test: #use this name in the adminer login screen server
    image: postgres:13.1
    container_name: postgres_forum_test
    restart: "no"
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  queue_cache_test:
    image: redis:alpine
    container_name: queue_cache_test
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - queue_cache_test_data:/data

  adminer_forum_test:
    image: adminer
    depends_on:
      - postgres_forum_test
    restart: always
    env_file:
      - .env.test
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  queue_cache_test_data: